import React, { useEffect, useRef } from 'react'
import './DesignDrawing.css'

/**
 * E-ink technical drawing panel. Populated by ui-bridge-mcp-server's ui://design resource
 * whenever the user asks Tau to design/sketch something (see MAIN_SYSTEM_PROMPT in
 * tau_core/llm/agent.py for the SVG accuracy contract Tau is held to). Sits beside the atom, never
 * on top of it - it is not a modal and never replaces the atom.
 *
 * Phase 6.F: App.jsx mounts this only while there IS an active design, so the atom gets the whole
 * stage the rest of the time. The old IdleDashboard fallback is gone - its status readouts are in
 * the toolbar now, and its task line is covered by the model-activity indicator under the atom.
 */
export default function DesignDrawing({ design }) {
  const svgWrapRef = useRef(null)

  // "Draw" the SVG in with a technical-pen stroke animation: compute each element's actual
  // path length and animate stroke-dashoffset from that length to 0, staggered per element.
  // This works on arbitrary LLM-generated SVG (not just pre-authored paths with known
  // dashoffsets), which a plain CSS keyframe animation couldn't do.
  useEffect(() => {
    const container = svgWrapRef.current
    if (!container) return
    const svgEl = container.querySelector('svg')
    if (!svgEl) return

    const drawable = svgEl.querySelectorAll('path, line, polyline, polygon, circle, rect')
    drawable.forEach((el, i) => {
      let length = 200
      try {
        if (typeof el.getTotalLength === 'function') {
          length = el.getTotalLength()
        }
      } catch {
        // Some elements (e.g. <rect> in older WebKit) may not support getTotalLength;
        // fall back to a fixed length so the animation still plays, just less precisely timed.
      }
      el.style.strokeDasharray = `${length}`
      el.style.strokeDashoffset = `${length}`
      el.style.transition = 'none'
      void el.getBoundingClientRect() // force reflow before re-enabling the transition
      el.style.transition = `stroke-dashoffset 0.6s ease-out ${i * 0.08}s`
      requestAnimationFrame(() => {
        el.style.strokeDashoffset = '0'
      })
    })
  }, [design?.svg, design?.updated_at])

  if (!design || !design.active) return null

  return (
    <div className="design-container">
      <div className="design-header">
        <span className="design-title">{design.title || 'UNTITLED DESIGN'}</span>
      </div>

      <div className="design-body">
        {design.svg ? (
          <div
            key={design.updated_at}
            ref={svgWrapRef}
            className="design-svg-wrap"
            // Content is generated by Tau's own LLM agent, not arbitrary external/user HTML;
            // the SVG contract in the system prompt restricts it to stroke-only shapes/text.
            dangerouslySetInnerHTML={{ __html: design.svg }}
          />
        ) : (
          <pre className="design-ascii">{design.ascii_art}</pre>
        )}
      </div>

      {design.description && <div className="design-description">{design.description}</div>}
    </div>
  )
}
