import React, { useEffect, useRef, useState } from 'react'
import './RecognitionCard.css'

const AUTO_DISMISS_MS = 8000

/**
 * Transient "USER RECOGNIZED" e-ink portrait card. Populated by ui-bridge-mcp-server's
 * ui://recognition resource when Tau identifies a known person (see MAIN_SYSTEM_PROMPT in
 * tau_core/llm/agent.py for the portrait-caching contract - the svg here is either a cached
 * portrait from memory-mcp-server or one Tau just drew). Unlike ApprovalQueue this never
 * blocks interaction, and unlike DesignDrawing it isn't a permanent panel: it appears in a
 * corner for a few seconds after recognized_at and then dismisses itself.
 */
export default function RecognitionCard({ recognition }) {
  const svgWrapRef = useRef(null)
  const [dismissed, setDismissed] = useState(false)

  // A new recognition event (recognized_at changes) un-dismisses the card and restarts the
  // auto-dismiss timer, even if the previous card for a different person was just closed.
  useEffect(() => {
    setDismissed(false)
    if (!recognition?.active || !recognition?.recognized_at) return undefined
    const timer = setTimeout(() => setDismissed(true), AUTO_DISMISS_MS)
    return () => clearTimeout(timer)
  }, [recognition?.recognized_at, recognition?.active])

  // Same technical-pen stroke-draw-in animation as DesignDrawing, applied to the portrait.
  useEffect(() => {
    const container = svgWrapRef.current
    if (!container) return
    const svgEl = container.querySelector('svg')
    if (!svgEl) return

    const drawable = svgEl.querySelectorAll('path, line, polyline, polygon, circle, rect, ellipse')
    drawable.forEach((el, i) => {
      let length = 150
      try {
        if (typeof el.getTotalLength === 'function') {
          length = el.getTotalLength()
        }
      } catch {
        // Some elements (e.g. <rect>/<ellipse> in older WebKit) may not support
        // getTotalLength; fall back to a fixed length so the animation still plays.
      }
      el.style.strokeDasharray = `${length}`
      el.style.strokeDashoffset = `${length}`
      el.style.transition = 'none'
      void el.getBoundingClientRect() // force reflow before re-enabling the transition
      el.style.transition = `stroke-dashoffset 0.5s ease-out ${i * 0.05}s`
      requestAnimationFrame(() => {
        el.style.strokeDashoffset = '0'
      })
    })
  }, [recognition?.svg, recognition?.recognized_at])

  if (!recognition || !recognition.active || dismissed) return null

  return (
    <div className="recognition-card-overlay">
      <div className="recognition-card">
        <button
          type="button"
          className="recognition-close"
          onClick={() => setDismissed(true)}
          aria-label="Dismiss"
        >
          ✕
        </button>

        <div className="recognition-portrait">
          {recognition.svg ? (
            <div
              key={recognition.recognized_at}
              ref={svgWrapRef}
              className="recognition-svg-wrap"
              // Content is generated by Tau's own LLM agent (or cached verbatim from a prior
              // generation), not arbitrary external/user HTML - same trust boundary as
              // DesignDrawing's svg.
              dangerouslySetInnerHTML={{ __html: recognition.svg }}
            />
          ) : (
            <pre className="recognition-ascii">{recognition.ascii_art}</pre>
          )}
        </div>

        <div className="recognition-label">USER RECOGNIZED</div>
        <div className="recognition-role">{recognition.role || 'UNKNOWN'}</div>
      </div>
    </div>
  )
}
